// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Hi6H-kTOU7KOkeqM_KlCtU-WLciYeM0',
    appId: '1:1061767952891:web:cba3f5618842c489cf335e',
    messagingSenderId: '1061767952891',
    projectId: 'medicinsschedules',
    authDomain: 'medicinsschedules.firebaseapp.com',
    storageBucket: 'medicinsschedules.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHA3iGQmLuvZyZCDauvcFpSZbuquNqNOY',
    appId: '1:1061767952891:android:257d18b4d71fd79ecf335e',
    messagingSenderId: '1061767952891',
    projectId: 'medicinsschedules',
    storageBucket: 'medicinsschedules.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQEkEwvm6I7NuCadYWNP5DDvm3Gh5i20',
    appId: '1:1061767952891:ios:934cee471b2d2e76cf335e',
    messagingSenderId: '1061767952891',
    projectId: 'medicinsschedules',
    storageBucket: 'medicinsschedules.firebasestorage.app',
    iosBundleId: 'com.example.medicinsSchedules',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQEkEwvm6I7NuCadYWNP5DDvm3Gh5i20',
    appId: '1:1061767952891:ios:934cee471b2d2e76cf335e',
    messagingSenderId: '1061767952891',
    projectId: 'medicinsschedules',
    storageBucket: 'medicinsschedules.firebasestorage.app',
    iosBundleId: 'com.example.medicinsSchedules',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Hi6H-kTOU7KOkeqM_KlCtU-WLciYeM0',
    appId: '1:1061767952891:web:d869b16e02c6aa73cf335e',
    messagingSenderId: '1061767952891',
    projectId: 'medicinsschedules',
    authDomain: 'medicinsschedules.firebaseapp.com',
    storageBucket: 'medicinsschedules.firebasestorage.app',
  );
}
