// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjQ08TqzEaGguBCfZCRqcBl9L4nyI2L9U',
    appId: '1:1067714145613:web:63357612ce95e7251d9b04',
    messagingSenderId: '1067714145613',
    projectId: 'flutterfirebase-c05b6',
    authDomain: 'flutterfirebase-c05b6.firebaseapp.com',
    storageBucket: 'flutterfirebase-c05b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DicHqH95QUGTNXQeoQ-ISKhl0rE5Y18',
    appId: '1:1067714145613:android:84882f3250b9a2dc1d9b04',
    messagingSenderId: '1067714145613',
    projectId: 'flutterfirebase-c05b6',
    storageBucket: 'flutterfirebase-c05b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsPEpH9-slHPdvSvShW3f5NDDsXf8fQEY',
    appId: '1:1067714145613:ios:e1cae2f7f21e741b1d9b04',
    messagingSenderId: '1067714145613',
    projectId: 'flutterfirebase-c05b6',
    storageBucket: 'flutterfirebase-c05b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsPEpH9-slHPdvSvShW3f5NDDsXf8fQEY',
    appId: '1:1067714145613:ios:e1cae2f7f21e741b1d9b04',
    messagingSenderId: '1067714145613',
    projectId: 'flutterfirebase-c05b6',
    storageBucket: 'flutterfirebase-c05b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjQ08TqzEaGguBCfZCRqcBl9L4nyI2L9U',
    appId: '1:1067714145613:web:5b6f1be019f211821d9b04',
    messagingSenderId: '1067714145613',
    projectId: 'flutterfirebase-c05b6',
    authDomain: 'flutterfirebase-c05b6.firebaseapp.com',
    storageBucket: 'flutterfirebase-c05b6.firebasestorage.app',
  );
}
